"""
This is a setup.py script generated by py2applet

Created via:
    /Users/cstout16/Library/Python/3.9/bin/py2applet --make-setup flashcards.py

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["../main.py"]
DATA_FILES = []
OPTIONS = {
    "iconfile": "../img/paau2_image.icns",
}

setup(
    app=APP,
    name="Flashcards",
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
